  CREATE TABLE `node` (
  `NODE_ID` varchar(255) NOT NULL,
  `NODE_NAME` varchar(255) NOT NULL,
  `NODE_TYPE` tinyint(4) DEFAULT '1',
  `PARENT_ID` varchar(255) DEFAULT NULL,
  `CREATE_TIME` DATETIME,
  `UPDATE_TIME` TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`NODE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;